### ISSUE TITLE
1.b | As a user, I want to be able to login using OAuth via GitHub

### ISSUE THREAD

**Issue by 0xjogge** [ITU-BDSA2024-GROUP17/Chirp#124]
# Description
A user should be able to login using UAuth via GitHub, which would allow the user to access (and use) the site without a password.

# Requirement Description
A GitHub OAuth provider should be added to the project, which will allow users to login using their GitHub account. The secrets need to be store securely and should therefor NOT be pushed to the code repo.

# Acceptence criteria
- [x] Configure the OAuth application on GitHub
- [x] Add OAuth GitHub provider package
- [x] Update programs.cs to use the new provider
- [x] Use GitHub secrets to store the OAuth application secrets
- [x] Add secrets to Azure App Service
 
# Resources
- [GitHub Oauth provider package](https://www.nuget.org/packages/AspNet.Security.OAuth.GitHub)
- [Link to requirement session notes](https://github.com/itu-bdsa/lecture_notes/blob/main/sessions/session_08/README_PROJECT.md#1b-oauth-via-github)

**Comment by johannes67890** [comment]
#127 Pulled in - Only need to `Add secrets to Azure App Service` now

**Comment by johannes67890** [comment]
> What is the status on the Azure App secrets?

I don't have access to Azure - we fix later this week 😸
