### ISSUE TITLE
As a manager i want to ensure that users can't send cheeps longer than 160 characters

### ISSUE THREAD

**Issue by Hopsasasa** [ITU-BDSA2024-GROUP17/Chirp#140]
Make sure that an individual using our Chirp! web-application can't send cheeps longer than 160 characters. This has to be exactly 160 characters. Not 159.

- [x] Dobbelt check previous work done on cheep limitation

**Comment by nicklasbns** [comment]
Checked that cheeps cannot be sent if they are over 160, but cheeps that are exactly 160 or below can be sent. The ui also responds properly
