### ISSUE TITLE
As a developer, I want to test everything major in my program 

### ISSUE THREAD

**Issue by nicklasbns** [ITU-BDSA2024-GROUP17/Chirp#185]
# Description
Make Unit, Integration and E2E test for various parts of the program

# Acceptence criteria
Make test for following parts of the code
## Chirp.Core
- [x] DTO - Ensure only the right fields gets transfered with the DTO's
## Chirp.Infrastructure
- [x]  Extensions/QueryableExtensions.cs
- [x] CheepRepository.cs
- [x] AuthorRepository.cs
- [x] CheepDbContext.cs
# Chirp.Web (Integration Tests)
## Public.cshtml.cs
- [x] Follow
- [x] Like
- [x] Comment
- [x] Pagination
# Chrip.Web.Playwright
- [x] Login/Logout
- [x] Account Timeline
- [x] User Timeline
- [x] Search
- [x] Edit Avatar
- [x] Comment cheep
- [x] Like cheep
- [x] Delete cheep
- [x] Edit cheep
- [x] View revisions

**Comment by nicklasbns** [comment]
Spurb has claimed "Edit Avatat"

I claim: "Like Cheep", "User Timeline" og "Follow User" (Not in the list)

**Comment by johannes67890** [comment]
I'm doing Repositories
