### ISSUE TITLE
As a student, I want the "Team work" section to be written.

### ISSUE THREAD

**Issue by 0xjogge** [ITU-BDSA2024-GROUP17/Chirp#229]
# Description
Write the "Team work" section such that it is ready to be put into the report.

# Requirement Description
Show a screenshot of your project board right before hand-in. Briefly describe which tasks are still unresolved, i.e., which features are missing from your applications or which functionality is incomplete.

Briefly describe and illustrate the flow of activities that happen from the new creation of an issue (task description), over development, etc. until a feature is finally merged into the main branch of your repository.

# Acceptence criteria
- [x] Write the section
- [x] Proofread the write section for both typos and factual mistakes
- [x] Add screenshot of project board and describe unresolved tasks

**OPTIONAL:**
- [x] Add flow diagram
# Resources
- [Report requirements](https://github.com/itu-bdsa/lecture_notes/blob/main/sessions/session_12/README_REPORT.md)

**Comment by Spurberino** [comment]
I wrote a good chunk of text for this, but am thinking about cutting it down a bit and adding a flow diagram.

**Comment by Spurberino** [comment]
Still need to screenshot the project board and describe unfinished tasks. Will need to do that at the end most likely.
