### ISSUE TITLE
As a student, I want the "LLMs, ChatGPT, CoPilot, and others" section to be written.

### ISSUE THREAD

**Issue by 0xjogge** [ITU-BDSA2024-GROUP17/Chirp#233]
# Description
Write the "LLMs, ChatGPT, CoPilot, and others" section such that it is ready to be put into the report.

# Requirement Description
State which LLM(s) were used during development of your project. In case you were not using any, just state so. In case you were using an LLM to support your development, briefly describe when and how it was applied. Reflect in writing to which degree the responses of the LLM were helpful. Discuss briefly if application of LLMs sped up your development or if the contrary was the case.

# Acceptence criteria
- [ ] Write the section
- [ ] Proofread the write section for both typos and factual mistakes
# Resources
- [Report requirements](https://github.com/itu-bdsa/lecture_notes/blob/main/sessions/session_12/README_REPORT.md)

**Comment by johannes67890** [comment]
@Hopsasasa I used Github copilot to write my pull requests descriptions. (each pull request should have a _credit_ section on the description, if co-pilot was used)
