### ISSUE TITLE
As a user i would like to see what tab i am on when changing settings

### ISSUE THREAD

**Issue by Hopsasasa** [ITU-BDSA2024-GROUP17/Chirp#258]
When entering the settings menu within Chirp, the selected tab on the left side is overlayed with blue. This hides the text of the current tab, which should be visible.

- [ ] Current tab visible within the settings menu

**Comment by Spurberino** [comment]
Changing the color for the .active class to white fixes this, line 478 in `index.css`. 
I am unsure if this would have unintended effects?
